services:
    postgres:
        image: postgres:17-alpine3.20
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

    # minio:
    #     image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    #     container_name: minio
    #     ports:
    #         - '9000:9000'
    #         - '9001:9001'
    #     command: server /data --console-address ":9001"

volumes:
    postgres_data: {}