services:
    database:
        image: postgres:17-alpine3.20
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'

    minio:
        image: minio/minio:RELEASE.2025-02-18T16-25-55Z
        container_name: minio
        ports:
            - '9000:9000'
            - '9001:9001'
        command: server /data --console-address ":9001"
